
-----------------------------------------------------------------------
---- Automatically generated by generate_premake.py. Do not edit ! ----
-----------------------------------------------------------------------

project("libavcodec")
  uuid("9DB2830C-D326-48ED-B4CC-08EA6A1B7272")
  kind("StaticLib")
  language("C")
  ffmpeg_common()

  filter("files:not wmaprodec.c")
    warnings "Off"
  filter({})

  links({
    "libavutil",
  })

  -- libavcodec/Makefile:
  --   HEADERS:
  files({
    "ac3_parser.h",
    "adts_parser.h",
    "avcodec.h",
    "avdct.h",
    "bsf.h",
    "codec.h",
    "codec_desc.h",
    "codec_id.h",
    "codec_par.h",
    "d3d11va.h",
    "defs.h",
    "dirac.h",
    "dv_profile.h",
    "dxva2.h",
    "exif.h",
    "jni.h",
    "mediacodec.h",
    "packet.h",
    "qsv.h",
    "smpte_436m.h",
    "vdpau.h",
    "version.h",
    "version_major.h",
    "videotoolbox.h",
    "vorbis_parser.h",
  })
  --   OBJS:
  files({
    "ac3_parser.c",
    "adts_parser.c",
    "allcodecs.c",
    "avcodec.c",
    "avdct.c",
    "packet.c",
    "bitstream.c",
    "bitstream_filters.c",
    "bsf.c",
    "codec_desc.c",
    "codec_par.c",
    "d3d11va.c",
    "decode.c",
    "dirac.c",
    "dv_profile.c",
    "encode.c",
    "exif.c",
    "get_buffer.c",
    "imgconvert.c",
    "jni.c",
    "mathtables.c",
    "mediacodec.c",
    "mpeg12framerate.c",
    "options.c",
    "parser.c",
    "parsers.c",
    "profiles.c",
    "qsv_api.c",
    "raw.c",
    "threadprogress.c",
    "tiff_common.c",
    "utils.c",
    "version.c",
    "vlc.c",
    "vorbis_parser.c",
    "xiph.c",
    "faandct.c",
    "faanidct.c",
    "fdctdsp.c",
    "jfdctfst.c",
    "jfdctint.c",
    "idctdsp.c",
    "simple_idct.c",
    "jrevdct.c",
    "sinewin.c",
    "wma_freqs.c",
    "wmaprodec.c",
    "wma.c",
    "wma_common.c",
    "pthread.c",
    "pthread_slice.c",
    "pthread_frame.c",
  })
  filter({"platforms:Windows"})
  files({
    "file_open.c",
  })
  filter({})

  -- libavcodec/aarch64/Makefile:
  --   OBJS:
  filter({"platforms:Android-ARM64"})
  files({
    "aarch64/fdctdsp_init_aarch64.c",
    "aarch64/idctdsp_init_aarch64.c",
  })
  filter({})
  --   NEON-OBJS:
  filter({"platforms:Android-ARM64"})
  files({
    "aarch64/fdctdsp_neon.S",
    "aarch64/idctdsp_neon.S",
    "aarch64/simple_idct_neon.S",
  })
  filter({})

  -- libavcodec/x86/Makefile:
  --   OBJS:
  filter({"platforms:Android-x86_64 or platforms:Linux or platforms:Windows"})
  files({
    "x86/constants.c",
    "x86/fdctdsp_init.c",
    "x86/fdct.c",
  })
  filter({})
